export const ownerModels = [
  {
    id: "model-1",
    name: "Customer Churn Predictor",
    description: "Random Forest model for predicting customer churn with 89% accuracy.",
    category: "Machine Learning",
    visibility: "public",
    ownerName: "John Owner",
    ownerEmail: "owner@modelwatch.com",
    createdAt: "2026-01-12",
    updatedAt: "2026-04-01",
    updates: ["Thresholds refreshed", "Validation report added"],
    notes: ["Reviewed churn threshold sensitivity"],
    attributes: [
      { name: "Accuracy", value: "89%" },
      { name: "Precision", value: "0.87" },
      { name: "Recall", value: "0.84" },
      { name: "Model Type", value: "Random Forest" },
    ],
  },
  {
    id: "model-2",
    name: "Fraud Detection Monitor",
    description: "Ensemble fraud scoring model used to flag anomalous payment activity.",
    category: "Risk",
    visibility: "shared",
    ownerName: "John Owner",
    ownerEmail: "owner@modelwatch.com",
    createdAt: "2026-02-18",
    updatedAt: "2026-04-07",
    updates: ["Feature weights updated"],
    notes: ["False positive rate annotated", "Operational threshold recommendation"],
    attributes: [
      { name: "Precision", value: "0.91" },
      { name: "Recall", value: "0.78" },
      { name: "Latency", value: "180 ms" },
      { name: "Model Type", value: "Ensemble" },
    ],
  },
  {
    id: "model-3",
    name: "Sentiment Analysis BERT",
    description: "Fine-tuned BERT model for customer sentiment classification workflows.",
    category: "NLP",
    visibility: "private",
    ownerName: "John Owner",
    ownerEmail: "owner@modelwatch.com",
    createdAt: "2026-01-28",
    updatedAt: "2026-04-08",
    updates: ["Prompt pack revised", "Drift note attached", "Model card updated"],
    notes: [],
    attributes: [
      { name: "Accuracy", value: "92%" },
      { name: "Languages", value: "EN, AR" },
      { name: "Model Type", value: "Transformer" },
      { name: "Confidence Threshold", value: "0.72" },
    ],
  },
  {
    id: "model-4",
    name: "Inventory Demand Forecaster",
    description: "Forecasting model for weekly inventory demand across retail channels.",
    category: "Forecasting",
    visibility: "shared",
    ownerName: "Sarah Analyst",
    ownerEmail: "analyst@modelwatch.com",
    createdAt: "2026-02-03",
    updatedAt: "2026-04-05",
    updates: ["Seasonality review completed"],
    notes: ["Forecast drift summary"],
    attributes: [
      { name: "MAPE", value: "7.4%" },
      { name: "Forecast Horizon", value: "12 weeks" },
      { name: "Model Type", value: "XGBoost" },
      { name: "Regions", value: "5" },
    ],
  },
  {
    id: "model-5",
    name: "Lead Scoring Engine",
    description: "Classification model for ranking sales leads by conversion likelihood.",
    category: "Sales",
    visibility: "public",
    ownerName: "Sarah Analyst",
    ownerEmail: "analyst@modelwatch.com",
    createdAt: "2026-03-10",
    updatedAt: "2026-04-06",
    updates: ["Calibration pass completed", "Campaign mapping updated"],
    notes: ["Lead quality segmentation note"],
    attributes: [
      { name: "Accuracy", value: "86%" },
      { name: "AUC", value: "0.91" },
      { name: "Model Type", value: "Gradient Boosting" },
      { name: "Segments", value: "12" },
    ],
  },
];

export const ownerCategories = [
  { id: "category-1", name: "Machine Learning" },
  { id: "category-2", name: "Risk" },
  { id: "category-3", name: "NLP" },
  { id: "category-4", name: "Forecasting" },
  { id: "category-5", name: "Sales" },
];
